// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiPowerTools.ScheduledJobsInsights.Data;

#nullable disable

namespace OptiPowerTools.ScheduledJobsInsights.Data.Migrations
{
    [DbContext(typeof(ScheduledJobsInsightsDbContext))]
    [Migration("20260824153053_DropUnusedScheduledJobIdIndex")]
    partial class DropUnusedScheduledJobIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduled_jobs_insights")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScheduledJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("JobTypeName", "StartedAt");

                    b.HasIndex("StartedAt", "Id")
                        .IsDescending();

                    b.HasIndex("JobName", "StartedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("Status", "StartedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("JobExecutions", "scheduled_jobs_insights");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("JobExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("JobExecutionId", "Sequence")
                        .IsUnique();

                    b.ToTable("JobLogEntries", "scheduled_jobs_insights");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("JobExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("JobExecutionId", "Name");

                    b.ToTable("JobMetrics", "scheduled_jobs_insights");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobRetentionPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RetentionDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobTypeName")
                        .IsUnique();

                    b.ToTable("JobRetentionPolicies", "scheduled_jobs_insights");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobLogEntry", b =>
                {
                    b.HasOne("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobExecution", "JobExecution")
                        .WithMany("LogEntries")
                        .HasForeignKey("JobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobExecution");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobMetric", b =>
                {
                    b.HasOne("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobExecution", "JobExecution")
                        .WithMany("Metrics")
                        .HasForeignKey("JobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobExecution");
                });

            modelBuilder.Entity("OptiPowerTools.ScheduledJobsInsights.Data.Entities.JobExecution", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
